"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertTriangle, ShieldAlert, ScrollText, BarChart3, Syringe, Check, X, Search, Activity,
} from "lucide-react";
import ImportExportMenu from "@/components/ui/import-export-menu";
import type { ImportResult } from "@/components/ui/csv-import-modal";
import FilterBar from "@/components/filters/filter-bar";
import { dateStamp, downloadCsv, printTable, type ExportCell } from "@/lib/export";
import { inDateRange } from "@/lib/daterange";

// ============================================================================
// Pharmacy Compliance — NAFDAC controlled-drug register, hash-chained
// dispensing audit, regulatory alerts and statutory report exports.
// ============================================================================

const inputCls =
  "w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2.5 text-sm outline-none transition-colors duration-200 focus:border-[var(--color-primary)]";
const btnPrimary =
  "focus-ring inline-flex items-center gap-1.5 rounded-lg bg-[var(--color-primary)] px-3 py-2 text-xs font-semibold text-white transition-colors duration-200 hover:bg-[var(--color-primary-dark)] disabled:opacity-60";
const btnGhost =
  "focus-ring inline-flex items-center gap-1.5 rounded-lg border border-[var(--color-border)] px-3 py-2 text-xs font-medium text-[var(--color-muted-fg)] transition-colors duration-200 hover:bg-slate-50 disabled:opacity-60";

const blockedImport = (label: string): ImportResult => ({
  created: 0,
  failed: 0,
  errors: [`${label} is generated by the system and cannot be imported.`],
});

function rowsAsExport(rows: Array<Record<string, unknown>>): { columns: string[]; rows: ExportCell[][] } {
  const columns = rows.length ? Object.keys(rows[0]) : [];
  return {
    columns,
    rows: rows.map((r) => columns.map((c) => {
      const v = r[c];
      if (v == null || typeof v === "string" || typeof v === "number") return v;
      return JSON.stringify(v);
    })),
  };
}
const fmt = (iso?: string | null) => (iso ? new Date(iso).toLocaleString() : "—");

type Tab = "alerts" | "register" | "audit" | "dispense" | "reports";

const TABS: Array<{ id: Tab; label: string; icon: typeof AlertTriangle }> = [
  { id: "alerts", label: "Alerts", icon: AlertTriangle },
  { id: "register", label: "Controlled register", icon: ScrollText },
  { id: "audit", label: "Audit trail", icon: ShieldAlert },
  { id: "dispense", label: "Dispense", icon: Syringe },
  { id: "reports", label: "NAFDAC reports", icon: BarChart3 },
];

interface AlertRow {
  id: string;
  alert_type: string;
  severity: string;
  title: string;
  message: string;
  status: string;
  created_at: string;
  pharmacy_drugs: { name: string; control_schedule: string | null; nafdac_number: string | null } | null;
}

interface RegRow {
  id: string;
  drug_id: string;
  patient_id: string | null;
  prescription_id: string | null;
  quantity_dispensed: number;
  quantity_received: number;
  balance_after: number;
  prescriber_name: string | null;
  notes: string | null;
  created_at: string;
  pharmacy_drugs: { name: string; control_schedule: string | null } | null;
  patients: { patient_number: string; first_name: string; last_name: string } | null;
  users: { full_name: string } | null;
}

interface LogRow {
  id: number;
  action: string;
  drug_name: string;
  quantity: number;
  batch_id: string | null;
  patient_id: string | null;
  prescription_id: string | null;
  notes: string | null;
  hash: string;
  prev_hash: string | null;
  created_at: string;
  users: { full_name: string } | null;
}

interface DrugRow {
  id: string;
  name: string;
  nafdac_number: string | null;
  control_schedule: string | null;
  max_qty_per_dispense: number | null;
  reorder_level: number;
  on_hand: number;
  register_balance: number | null;
  low: boolean;
}

const sevStyle = (s: string) =>
  s === "critical"
    ? "bg-red-50 text-red-700 ring-1 ring-red-200"
    : s === "warning"
      ? "bg-amber-50 text-amber-700 ring-1 ring-amber-200"
      : "bg-sky-50 text-sky-700 ring-1 ring-sky-200";

export default function PharmacyComplianceView() {
  const [tab, setTab] = useState<Tab>("alerts");

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-xl font-bold text-[var(--color-foreground)]">Pharmacy compliance</h2>
          <p className="mt-0.5 text-sm text-[var(--color-muted-fg)]">
            NAFDAC control register, tamper-proof audit trail, regulatory alerts and stat reports.
          </p>
        </div>
        <div className="flex gap-2" role="group" aria-label="Compliance section">
          {TABS.map((t) => (
            <button
              key={t.id}
              type="button"
              onClick={() => setTab(t.id)}
              aria-pressed={tab === t.id}
              className={`focus-ring inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold transition-colors duration-200 ${
                tab === t.id ? "bg-[var(--color-primary)] text-white" : "border border-[var(--color-border)] text-[var(--color-muted-fg)] hover:bg-slate-50"
              }`}
            >
              <t.icon size={14} aria-hidden="true" />
              {t.label}
            </button>
          ))}
        </div>
      </div>

      {tab === "alerts" && <AlertsTab />}
      {tab === "register" && <RegisterTab />}
      {tab === "audit" && <AuditTab />}
      {tab === "dispense" && <DispenseTab />}
      {tab === "reports" && <ReportsTab />}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Alerts
// ---------------------------------------------------------------------------
function AlertsTab() {
  const [rows, setRows] = useState<AlertRow[]>([]);
  const [status, setStatus] = useState("open");
  const [loading, setLoading] = useState(true);
  const [msg, setMsg] = useState("");
  const [search, setSearch] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  const load = useCallback(async (stat = status) => {
    setLoading(true);
    try {
      const res = await fetch(`/api/pharmacy/compliance/alerts?pageSize=100${stat ? `&status=${stat}` : ""}`, { cache: "no-store" });
      const j = await res.json();
      setRows(j.data ?? []);
    } catch {
      setRows([]);
    } finally {
      setLoading(false);
    }
  }, [status]);

  useEffect(() => { void load(); }, [load]);

  const resolve = async (a: AlertRow, st: "acknowledged" | "resolved") => {
    const res = await fetch("/api/pharmacy/compliance/alerts", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id: a.id, status: st }),
    });
    if (!res.ok) { setMsg((await res.json()).error ?? "Failed"); return; }
    void load();
  };

  const visible = rows.filter((a) => {
    const q = search.trim().toLowerCase();
    const matchesSearch =
      !q ||
      a.alert_type.toLowerCase().includes(q) ||
      a.message.toLowerCase().includes(q) ||
      a.severity.toLowerCase().includes(q) ||
      (a.pharmacy_drugs?.name ?? "").toLowerCase().includes(q);
    return matchesSearch && inDateRange(a.created_at, from, to);
  });

  const { columns: alertCols, rows: alertRows } = rowsAsExport(
    visible.map((a) => ({
      alert_type: a.alert_type, severity: a.severity, drug: a.pharmacy_drugs?.name ?? "",
      message: a.message, raised_at: a.created_at, status: a.status,
    }))
  );

  function exportCsv() {
    if (visible.length === 0) { alert("Nothing to export — no alerts yet."); return; }
    downloadCsv(`compliance-alerts-${dateStamp()}.csv`, alertCols, alertRows);
  }

  function exportPdf() {
    if (visible.length === 0) { alert("Nothing to export — no alerts yet."); return; }
    printTable("Pharmacy Compliance Alerts", alertCols, alertRows);
  }

  return (
    <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="font-semibold text-[var(--color-foreground)]">Regulatory alerts</h3>
          <p className="text-xs text-[var(--color-muted-fg)]">Low controlled stock, expiring stock, invalid registration and suspicious dispensing patterns.</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex gap-1">
            {["open", "acknowledged", "resolved", ""].map((s) => (
              <button key={s || "all"} type="button" onClick={() => setStatus(s)}
                className={`focus-ring rounded-lg px-2.5 py-1.5 text-xs font-semibold ${status === s ? "bg-[var(--color-primary)] text-white" : "border border-[var(--color-border)] text-[var(--color-muted-fg)]"}`}>
                {s || "all"}
              </button>
            ))}
          </div>
          <ImportExportMenu
            entityLabel="Compliance Alerts"
            exportCsv={exportCsv}
            exportPdf={exportPdf}
            importColumns={alertCols}
            templateFilename="compliance-alerts-import-template.csv"
            onImport={async () => blockedImport("Compliance alerts")}
          />
        </div>
      </div>
      <div className="mb-4">
        <FilterBar
          query={search}
          onQueryChange={setSearch}
          from={from}
          to={to}
          onFromChange={setFrom}
          onToChange={setTo}
          onClear={() => { setSearch(""); setFrom(""); setTo(""); }}
          searchPlaceholder="Search type, drug, severity or message…"
          searchWidth={280}
        />
      </div>
      {msg && <p className="mb-3 text-sm text-red-600">{msg}</p>}
      {loading ? <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">Loading alerts…</p> : visible.length === 0 ? (
        <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">No alerts match this filter.</p>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-[var(--color-border)] text-xs uppercase tracking-wide text-[var(--color-muted-fg)]">
              <tr>
                <th className="py-2 pr-3 font-semibold">Type</th>
                <th className="py-2 pr-3 font-semibold">Drug</th>
                <th className="py-2 pr-3 font-semibold">Severity</th>
                <th className="py-2 pr-3 font-semibold">Message</th>
                <th className="py-2 pr-3 font-semibold">Raised</th>
                <th className="py-2 font-semibold">Status</th>
                <th className="py-2 font-semibold">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--color-border)]">
              {visible.map((a) => (
                <tr key={a.id}>
                  <td className="py-2.5 pr-3 font-medium text-[var(--color-foreground)]">{a.alert_type}</td>
                  <td className="py-2.5 pr-3 text-[var(--color-muted-fg)]">{a.pharmacy_drugs?.name ?? "—"}</td>
                  <td className="py-2.5 pr-3"><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${sevStyle(a.severity)}`}>{a.severity}</span></td>
                  <td className="py-2.5 pr-3 text-[var(--color-muted-fg)]">{a.message}</td>
                  <td className="py-2.5 pr-3 text-xs text-[var(--color-muted-fg)]">{fmt(a.created_at)}</td>
                  <td className="py-2.5 pr-3 text-xs text-[var(--color-muted-fg)]">{a.status}</td>
                  <td className="py-2.5">
                    <div className="flex gap-1.5">
                      {a.status === "open" && (
                        <button type="button" onClick={() => void resolve(a, "acknowledged")} className={btnGhost}>Acknowledge</button>
                      )}
                      {a.status !== "resolved" && (
                        <button type="button" onClick={() => void resolve(a, "resolved")} className={btnPrimary}><Check size={12} />Resolve</button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Controlled register
// ---------------------------------------------------------------------------
function RegisterTab() {
  const [rows, setRows] = useState<RegRow[]>([]);
  const [drugs, setDrugs] = useState<DrugRow[]>([]);
  const [drugId, setDrugId] = useState("");
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  const load = useCallback(async (did = drugId) => {
    setLoading(true);
    try {
      const [rRes, dRes] = await Promise.all([
        fetch(`/api/pharmacy/compliance/register?pageSize=200${did ? `&drugId=${did}` : ""}`, { cache: "no-store" }),
        fetch("/api/pharmacy/controlled-drugs", { cache: "no-store" }),
      ]);
      const r = await rRes.json();
      const d = await dRes.json();
      setRows(r.data ?? []);
      setDrugs(d.data ?? []);
    } catch { /* noop */ } finally { setLoading(false); }
  }, [drugId]);

  useEffect(() => { void load(); }, [load]);

  const patientLabel = (r: RegRow) =>
    r.patients ? `${r.patients.first_name} ${r.patients.last_name}` : r.prescription_id ? "(Rx)" : "—";

  const visible = rows.filter((r) => {
    const q = search.trim().toLowerCase();
    const matchesSearch =
      !q ||
      (r.pharmacy_drugs?.name ?? "").toLowerCase().includes(q) ||
      patientLabel(r).toLowerCase().includes(q) ||
      (r.prescriber_name ?? "").toLowerCase().includes(q);
    return matchesSearch && inDateRange(r.created_at, from, to);
  });

  const { columns: regCols, rows: regRows } = rowsAsExport(
    visible.map((r) => ({
      when: r.created_at,
      drug: r.pharmacy_drugs?.name ?? "",
      patient: patientLabel(r),
      qty_in: r.quantity_received ?? "",
      qty_out: r.quantity_dispensed ?? "",
      balance_after: r.balance_after,
      prescriber: r.prescriber_name ?? "",
      logged_by: r.users?.full_name ?? "system",
    }))
  );

  function exportCsv() {
    if (visible.length === 0) { alert("Nothing to export — no register entries yet."); return; }
    downloadCsv(`controlled-register-${dateStamp()}.csv`, regCols, regRows);
  }

  function exportPdf() {
    if (visible.length === 0) { alert("Nothing to export — no register entries yet."); return; }
    printTable("NAFDAC Controlled Drug Register", regCols, regRows);
  }

  return (
    <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="font-semibold text-[var(--color-foreground)]">Controlled drug register</h3>
          <p className="text-xs text-[var(--color-muted-fg)]">Append-only ledger — every controlled movement with running balance. Corrections are new rows.</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <select className={inputCls + " w-auto"} value={drugId} onChange={(e) => setDrugId(e.target.value)}>
            <option value="">All controlled drugs</option>
            {drugs.map((d) => (
              <option key={d.id} value={d.id}>{d.name} {d.low && "· LOW"}</option>
            ))}
          </select>
          <ImportExportMenu
            entityLabel="Controlled Register"
            exportCsv={exportCsv}
            exportPdf={exportPdf}
            importColumns={regCols}
            templateFilename="controlled-register-import-template.csv"
            onImport={async () => blockedImport("The controlled drug register")}
          />
        </div>
      </div>
      <div className="mb-4">
        <FilterBar
          query={search}
          onQueryChange={setSearch}
          from={from}
          to={to}
          onFromChange={setFrom}
          onToChange={setTo}
          onClear={() => { setSearch(""); setFrom(""); setTo(""); }}
          searchPlaceholder="Search drug, patient or prescriber…"
          searchWidth={280}
        />
      </div>
      {loading ? (
        <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">Loading register…</p>
      ) : visible.length === 0 ? (
        <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">No register entries yet.</p>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-[var(--color-border)] text-xs uppercase tracking-wide text-[var(--color-muted-fg)]">
              <tr>
                <th className="py-2 pr-3 font-semibold">When</th>
                <th className="py-2 pr-3 font-semibold">Drug</th>
                <th className="py-2 pr-3 font-semibold">Patient</th>
                <th className="py-2 pr-3 font-semibold">In</th>
                <th className="py-2 pr-3 font-semibold">Out</th>
                <th className="py-2 pr-3 font-semibold">Balance</th>
                <th className="py-2 pr-3 font-semibold">Prescriber</th>
                <th className="py-2 font-semibold">Logged by</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--color-border)]">
              {visible.map((r) => (
                <tr key={r.id}>
                  <td className="py-2.5 pr-3 text-xs text-[var(--color-muted-fg)]">{fmt(r.created_at)}</td>
                  <td className="py-2.5 pr-3">{r.pharmacy_drugs?.name ?? "—"}</td>
                  <td className="py-2.5 pr-3 text-[var(--color-muted-fg)]">
                    {patientLabel(r)}
                  </td>
                  <td className="py-2.5 pr-3 text-emerald-600">{r.quantity_received || "—"}</td>
                  <td className="py-2.5 pr-3 text-red-600">{r.quantity_dispensed || "—"}</td>
                  <td className="py-2.5 pr-3 font-semibold text-[var(--color-foreground)]">{r.balance_after}</td>
                  <td className="py-2.5 pr-3 text-[var(--color-muted-fg)]">{r.prescriber_name ?? "—"}</td>
                  <td className="py-2.5 text-[var(--color-muted-fg)]">{r.users?.full_name ?? "system"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Audit trail (hash-chained)
// ---------------------------------------------------------------------------
function AuditTab() {
  const [rows, setRows] = useState<LogRow[]>([]);
  const [verified, setVerified] = useState<{ verified: boolean; brokenAt: number | null; total: number } | null>(null);
  const [checking, setChecking] = useState(false);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/pharmacy/compliance/logs?pageSize=200", { cache: "no-store" });
      const j = await res.json();
      setRows(j.data?.rows ?? []);
    } catch { setRows([]); } finally { setLoading(false); }
  }, []);

  useEffect(() => { void load(); }, [load]);

  const verifyChain = async () => {
    setChecking(true);
    try {
      const res = await fetch("/api/pharmacy/compliance/logs?pageSize=1&verify=true", { cache: "no-store" });
      const j = await res.json();
      setVerified(j.data?.verified ?? null);
    } catch { setVerified(null); } finally { setChecking(false); }
  };

  const visible = rows.filter((r) => {
    const q = search.trim().toLowerCase();
    const matchesSearch =
      !q ||
      r.drug_name.toLowerCase().includes(q) ||
      r.action.toLowerCase().includes(q) ||
      (r.users?.full_name ?? "").toLowerCase().includes(q) ||
      r.hash.toLowerCase().includes(q);
    return matchesSearch && inDateRange(r.created_at, from, to);
  });

  const { columns: auditCols, rows: auditRows } = rowsAsExport(visible as unknown as Array<Record<string, unknown>>);

  function exportCsv() {
    if (visible.length === 0) { alert("Nothing to export — no audit entries yet."); return; }
    downloadCsv(`dispense-audit-${dateStamp()}.csv`, auditCols, auditRows);
  }

  function exportPdf() {
    if (visible.length === 0) { alert("Nothing to export — no audit entries yet."); return; }
    printTable("Pharmacy Dispensing Audit Trail", auditCols, auditRows);
  }

  return (
    <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="font-semibold text-[var(--color-foreground)]">H dispensing audit trail</h3>
          <p className="text-xs text-[var(--color-muted-fg)]">Every stock movement is appended with a linked SHA-256 hash. Rows cannot be edited or deleted.</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button type="button" onClick={() => void verifyChain()} disabled={checking} className={btnGhost}>
            {checking ? "Verifying…" : <><ShieldAlert size={13} />Verify full chain</>}
          </button>
          <ImportExportMenu
            entityLabel="Audit Trail"
            exportCsv={exportCsv}
            exportPdf={exportPdf}
            importColumns={auditCols}
            templateFilename="dispense-audit-import-template.csv"
            onImport={async () => blockedImport("The dispensing audit trail")}
          />
        </div>
      </div>
      <div className="mb-4">
        <FilterBar
          query={search}
          onQueryChange={setSearch}
          from={from}
          to={to}
          onFromChange={setFrom}
          onToChange={setTo}
          onClear={() => { setSearch(""); setFrom(""); setTo(""); }}
          searchPlaceholder="Search drug, action, actor or hash…"
          searchWidth={280}
        />
      </div>
      {verified && (
        <div className={`mb-4 flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium ${verified.verified ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>
          {verified.verified ? <><Check size={15} /> {verified.total.toLocaleString()} audit rows — hash chain verified unbroken</> : <><X size={15} /> Chain BROKEN at row {verified.brokenAt} — audit tampering possible</>}
        </div>
      )}
      {loading ? (
        <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">Loading audit trail…</p>
      ) : visible.length === 0 ? (
        <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">No movements logged yet.</p>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-[var(--color-border)] text-xs uppercase tracking-wide text-[var(--color-muted-fg)]">
              <tr>
                <th className="py-2 pr-3 font-semibold">#</th>
                <th className="py-2 pr-3 font-semibold">When</th>
                <th className="py-2 pr-3 font-semibold">Action</th>
                <th className="py-2 pr-3 font-semibold">Drug</th>
                <th className="py-2 pr-3 font-semibold">Qty</th>
                <th className="py-2 pr-3 font-semibold">Actor</th>
                <th className="py-2 font-semibold">Hash (truncated)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--color-border)]">
              {visible.map((r) => (
                <tr key={r.id}>
                  <td className="py-2.5 pr-3 text-xs text-[var(--color-muted-fg)]">#{r.id}</td>
                  <td className="py-2.5 pr-3 text-xs text-[var(--color-muted-fg)]">{fmt(r.created_at)}</td>
                  <td className="py-2.5 pr-3"><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${r.action === "in" ? "bg-emerald-50 text-emerald-700" : "bg-sky-50 text-sky-700"}`}>{r.action}</span></td>
                  <td className="py-2.5 pr-3">{r.drug_name}</td>
                  <td className="py-2.5 pr-3">{r.quantity}</td>
                  <td className="py-2.5 pr-3 text-[var(--color-muted-fg)]">{r.users?.full_name ?? "system"}</td>
                  <td className="py-2.5 font-mono text-xs text-[var(--color-muted-fg)]" title={r.hash}>{r.hash.slice(0, 16)}…</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Controlled dispensing
// ---------------------------------------------------------------------------
function DispenseTab() {
  const [drugs, setDrugs] = useState<DrugRow[]>([]);
  const [drugId, setDrugId] = useState("");
  const [patientId, setPatientId] = useState("");
  const [patients, setPatients] = useState<Array<{ id: string; first_name: string; last_name: string; patient_number: string }>>([]);
  const [qSearch, setQSearch] = useState("");
  const [rxs, setRxs] = useState<Array<{ id: string; status: string; issued_date: string; prescription_items: Array<{ id: string; pharmacy_drug_id: string | null; medication_name: string; quantity: number; dispensed_qty: number }> }>>([]);
  const [rxId, setRxId] = useState("");
  const [qty, setQty] = useState("");
  const [notes, setNotes] = useState("");
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<{ ok: boolean; text: string } | null>(null);
  const [lastDispense, setLastDispense] = useState<{ drug: string; qty: number; at: string } | null>(null);
  const [history, setHistory] = useState<RegRow[]>([]);
  const [search, setSearch] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  useEffect(() => {
    Promise.all([
      fetch("/api/pharmacy/controlled-drugs", { cache: "no-store" }).then((r) => r.json()),
      fetch("/api/pharmacy/compliance/register?pageSize=200", { cache: "no-store" }).then((r) => r.json()),
    ])
      .then(([d, r]) => {
        setDrugs(d.data ?? []);
        setHistory(((r.data ?? []) as RegRow[]).filter((row) => row.quantity_dispensed > 0));
      })
      .catch(() => setDrugs([]));
  }, []);

  const searchPatients = async () => {
    if (!qSearch.trim()) return;
    const res = await fetch(`/api/patients?q=${encodeURIComponent(qSearch.trim())}&pageSize=20`, { cache: "no-store" });
    const j = await res.json();
    setPatients(j.data ?? []);
  };

  const pickPatient = async (id: string) => {
    setPatientId(id);
    const res = await fetch(`/api/prescriptions?patient_id=${id}&status=active`, { cache: "no-store" });
    const j = await res.json();
    setRxs(j.data ?? []);
  };

  const drug = drugs.find((d) => d.id === drugId);

  const dispense = async () => {
    setMsg(null);
    if (!drugId || !rxId || !patientId || !(Number(qty) > 0)) {
      setMsg({ ok: false, text: "Drug, prescription, patient and a positive quantity are required." });
      return;
    }
    setBusy(true);
    try {
      const res = await fetch("/api/pharmacy/controlled-dispense", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ drugId, prescriptionId: rxId, patientId, quantity: Number(qty), notes }),
      });
      const j = await res.json();
      if (!res.ok) { setMsg({ ok: false, text: j.error ?? "Dispense failed" }); return; }
      setMsg({ ok: true, text: `Dispensed. ${j.data?.dispensed ?? 0} movement row(s) written.` });
      setLastDispense({ drug: drug?.name ?? drugId, qty: Number(qty), at: new Date().toLocaleString() });
      const fresh = await fetch("/api/pharmacy/controlled-drugs", { cache: "no-store" });
      setDrugs((await fresh.json()).data ?? []);
    } catch {
      setMsg({ ok: false, text: "Dispense request failed" });
    } finally {
      setBusy(false);
    }
  };

  const visibleDrugs = drugs.filter((d) => {
    const q = search.trim().toLowerCase();
    if (!q) return true;
    return (
      d.name.toLowerCase().includes(q) ||
      (d.control_schedule ?? "").toLowerCase().includes(q) ||
      (d.nafdac_number ?? "").toLowerCase().includes(q)
    );
  });

  const patientLabel = (r: RegRow) =>
    r.patients ? `${r.patients.first_name} ${r.patients.last_name}` : r.prescription_id ? "(Rx)" : "—";

  const visibleHistory = history.filter((h) => {
    const q = search.trim().toLowerCase();
    const matchesSearch =
      !q || (h.pharmacy_drugs?.name ?? "").toLowerCase().includes(q) || patientLabel(h).toLowerCase().includes(q);
    return matchesSearch && inDateRange(h.created_at, from, to);
  });

  return (
    <div className="space-y-5">
      <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
        <FilterBar
          query={search}
          onQueryChange={setSearch}
          from={from}
          to={to}
          onFromChange={setFrom}
          onToChange={setTo}
          onClear={() => { setSearch(""); setFrom(""); setTo(""); }}
          searchPlaceholder="Search drug, schedule or NAFDAC no…"
          searchWidth={300}
        />
        <p className="mt-2 text-xs text-[var(--color-muted-fg)]">
          Search filters the controlled formulary; the date range filters recent dispensings below.
        </p>
      </div>
      <div className="grid gap-5 lg:grid-cols-2">
      <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
        <h3 className="font-semibold text-[var(--color-foreground)]">Prescribed controlled doses</h3>
        <p className="mb-4 text-xs text-[var(--color-muted-fg)]">Enforced: NAFDAC registration, Rx must be active and match the patient, per-dispense cap, and auto-logs the chain.</p>

        <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">Controlled drug</label>
        <select className={inputCls} value={drugId} onChange={(e) => setDrugId(e.target.value)}>
          <option value="">Select drug…</option>
          {drugs.map((d) => (
            <option key={d.id} value={d.id} disabled={d.on_hand <= 0}>
              {d.name} · {d.control_schedule} · on hand {d.on_hand}{d.register_balance != null ? ` · register ${d.register_balance}` : ""}
            </option>
          ))}
        </select>
        {drug && (
          <div className="mt-2 flex flex-wrap gap-2 text-xs">
            <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[var(--color-muted-fg)]">NAFDAC {drug.nafdac_number ?? "—"}</span>
            <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[var(--color-muted-fg)]">cap {drug.max_qty_per_dispense ?? "—"}/dispense</span>
            <span className={drug.low ? "rounded-full bg-red-50 px-2 py-0.5 text-red-700" : "rounded-full bg-emerald-50 px-2 py-0.5 text-emerald-700"}>
              {drug.low ? "LOW STOCK" : `on hand ${drug.on_hand}`}
            </span>
          </div>
        )}

        <label className="mb-1 mt-4 block text-xs font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">Patient</label>
        <div className="flex gap-2">
          <input className={inputCls} placeholder="Search patient (name or no)…" value={qSearch} onChange={(e) => setQSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void searchPatients()} />
          <button type="button" onClick={() => void searchPatients()} className={btnGhost}><Search size={14} />Find</button>
        </div>
        {patients.length > 0 && (
          <ul className="mt-2 max-h-40 overflow-y-auto rounded-lg border border-[var(--color-border)]">
            {patients.map((p) => (
              <li key={p.id}>
                <button type="button" className="w-full px-3 py-2 text-left text-sm hover:bg-slate-50" onClick={() => void pickPatient(p.id)}>
                  {p.first_name} {p.last_name} <span className="text-xs text-[var(--color-muted-fg)]">#{p.patient_number}</span>
                </button>
              </li>
            ))}
          </ul>
        )}

        <label className="mb-1 mt-4 block text-xs font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">Prescription</label>
        <select className={inputCls} value={rxId} onChange={(e) => setRxId(e.target.value)}>
          <option value="">Select active Rx…</option>
          {rxs.map((rx) => (
            <option key={rx.id} value={rx.id}>Rx {rx.id.slice(0, 8)} · {rx.issued_date} · {rx.prescription_items?.length ?? 0} item(s)</option>
          ))}
        </select>

        <div className="mt-4 grid grid-cols-2 gap-3">
          <div>
            <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">Quantity</label>
            <input type="number" min={1} className={inputCls} value={qty} onChange={(e) => setQty(e.target.value)} />
          </div>
          <div>
            <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">Notes</label>
            <input className={inputCls} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="optional" />
          </div>
        </div>

        <button type="button" onClick={() => void dispense()} disabled={busy} className={btnPrimary + " mt-4 w-full justify-center py-2.5"}>
          <Syringe size={14} />{busy ? "Dispensing…" : "Dispense controlled dose"}
        </button>
        {msg && <p className={`mt-3 text-sm ${msg.ok ? "text-emerald-600" : "text-red-600"}`}>{msg.text}</p>}
      </div>

      <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
          <h3 className="font-semibold text-[var(--color-foreground)]">Controlled formulary health</h3>
          <ImportExportMenu
            entityLabel="Controlled Formulary"
            exportCsv={() => {
              if (drugs.length === 0) { alert("Nothing to export — no controlled drugs yet."); return; }
              const cols = ["name", "control_schedule", "on_hand", "register_balance", "max_qty_per_dispense", "nafdac_number", "low"];
              downloadCsv(`controlled-formulary-${dateStamp()}.csv`, cols,
                drugs.map((d) => [d.name, d.control_schedule, d.on_hand, d.register_balance ?? "", d.max_qty_per_dispense ?? "", d.nafdac_number ?? "", d.low ? "LOW" : "ok"]));
            }}
            exportPdf={() => {
              if (drugs.length === 0) { alert("Nothing to export — no controlled drugs yet."); return; }
              const cols = ["name", "control_schedule", "on_hand", "register_balance", "max_qty_per_dispense", "nafdac_number", "low"];
              printTable("Controlled Formulary Health", cols,
                drugs.map((d) => [d.name, d.control_schedule, d.on_hand, d.register_balance ?? "", d.max_qty_per_dispense ?? "", d.nafdac_number ?? "", d.low ? "LOW" : "ok"]));
            }}
            importColumns={["name", "control_schedule", "on_hand", "register_balance", "max_qty_per_dispense", "nafdac_number", "low"]}
            templateFilename="controlled-formulary-import-template.csv"
            onImport={async () => blockedImport("The controlled formulary")}
          />
        </div>
        {lastDispense && (
          <div className="mb-4 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">
            Last dispensed: {lastDispense.drug} ×{lastDispense.qty} at {lastDispense.at}
          </div>
        )}
        <div className="max-h-[480px] overflow-y-auto">
          <table className="w-full text-left text-sm">
            <thead className="sticky top-0 border-b border-[var(--color-border)] bg-white text-xs uppercase tracking-wide text-[var(--color-muted-fg)]">
              <tr>
                <th className="py-2 pr-3 font-semibold">Drug</th>
                <th className="py-2 pr-3 font-semibold">Schedule</th>
                <th className="py-2 pr-3 font-semibold">NAFDAC</th>
                <th className="py-2 pr-3 font-semibold">On hand</th>
                <th className="py-2 font-semibold">Register</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--color-border)]">
              {visibleDrugs.map((d) => (
                <tr key={d.id} className={d.low ? "bg-red-50" : undefined}>
                  <td className="py-2.5 pr-3">{d.name}</td>
                  <td className="py-2.5 pr-3 text-xs text-[var(--color-muted-fg)]">{d.control_schedule ?? "—"}</td>
                  <td className="py-2.5 pr-3 font-mono text-xs text-[var(--color-muted-fg)]">{d.nafdac_number ?? "—"}</td>
                  <td className="py-2.5 pr-3 font-semibold">{d.on_hand}{d.low ? " ⚠" : ""}</td>
                  <td className="py-2.5 text-[var(--color-muted-fg)]">{d.register_balance ?? "—"}</td>
                </tr>
              ))}
              {visibleDrugs.length === 0 && (
                <tr>
                  <td colSpan={5} className="py-8 text-center text-xs text-[var(--color-muted-fg)]">No controlled drugs match this search.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
      </div>

      <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
        <h3 className="font-semibold text-[var(--color-foreground)]">Recent controlled dispensing</h3>
        <p className="mb-3 text-xs text-[var(--color-muted-fg)]">Latest out-movements from the NAFDAC register — filtered by the search and date range above.</p>
        {visibleHistory.length === 0 ? (
          <p className="py-8 text-center text-sm text-[var(--color-muted-fg)]">No dispensing activity in this period.</p>
        ) : (
          <div className="max-h-[400px] overflow-auto">
            <table className="w-full text-left text-sm">
              <thead className="sticky top-0 border-b border-[var(--color-border)] bg-white text-xs uppercase tracking-wide text-[var(--color-muted-fg)]">
                <tr>
                  <th className="py-2 pr-3 font-semibold">When</th>
                  <th className="py-2 pr-3 font-semibold">Drug</th>
                  <th className="py-2 pr-3 font-semibold">Patient</th>
                  <th className="py-2 pr-3 font-semibold">Qty</th>
                  <th className="py-2 pr-3 font-semibold">Balance after</th>
                  <th className="py-2 font-semibold">Dispensed by</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--color-border)]">
                {visibleHistory.map((h) => (
                  <tr key={h.id}>
                    <td className="py-2.5 pr-3 text-xs text-[var(--color-muted-fg)]">{fmt(h.created_at)}</td>
                    <td className="py-2.5 pr-3">{h.pharmacy_drugs?.name ?? "—"}</td>
                    <td className="py-2.5 pr-3 text-[var(--color-muted-fg)]">{patientLabel(h)}</td>
                    <td className="py-2.5 pr-3 font-semibold text-red-600">{h.quantity_dispensed}</td>
                    <td className="py-2.5 pr-3 text-[var(--color-muted-fg)]">{h.balance_after}</td>
                    <td className="py-2.5 text-[var(--color-muted-fg)]">{h.users?.full_name ?? "system"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// NAFDAC reports
// ---------------------------------------------------------------------------
interface ReportRow {
  [key: string]: unknown;
}

function ReportsTab() {
  const [report, setReport] = useState<"usage" | "movements" | "expiry" | "supplier">("usage");
  const [from, setFrom] = useState(new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10));
  const [to, setTo] = useState(new Date().toISOString().slice(0, 10));
  const [days, setDays] = useState(90);
  const [rows, setRows] = useState<ReportRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState("");
  const [search, setSearch] = useState("");

  const run = async () => {
    setLoading(true);
    setMsg("");
    try {
      const params = new URLSearchParams({ report, from, to, days: String(days), includeExpired: "true" });
      if (report === "usage" || report === "movements") params.set("includeExpired", "false");
      const res = await fetch(`/api/pharmacy/compliance/reports?${params}`, { cache: "no-store" });
      const j = await res.json();
      if (!res.ok) { setMsg(j.error ?? "Report failed"); setRows([]); return; }
      setRows(j.data?.rows ?? []);
    } catch {
      setMsg("Report request failed");
      setRows([]);
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => { void run(); }, []);

  const exportCsv = () => {
    if (visibleRows.length === 0) return;
    const headers = Object.keys(visibleRows[0]).join(",");
    const lines = visibleRows.map((r) => Object.values(r).map((v) => `"${String(v ?? "").replace(/"/g, '""')}"`).join(","));
    const blob = new Blob([`${headers}\n${lines.join("\n")}`], { type: "text/csv;charset=utf-8;" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `compliance-${report}-${from}-to-${to}.csv`;
    document.body.appendChild(a);
    a.click();
    URL.revokeObjectURL(a.href);
    document.body.removeChild(a);
  };

  const columns = useMemo(() => (rows.length ? Object.keys(rows[0]) : []), [rows]);

  const visibleRows = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return rows;
    return rows.filter((r) => columns.some((c) => String(r[c] ?? "").toLowerCase().includes(q)));
  }, [rows, search, columns]);

  const reportRows = () => visibleRows.map((r) => columns.map((c) => {
    const v = r[c];
    if (v == null || typeof v === "string" || typeof v === "number") return v;
    return JSON.stringify(v);
  }));

  function exportPdf() {
    if (visibleRows.length === 0) { alert("Nothing to export — run the report first."); return; }
    printTable(`NAFDAC ${report} report — ${from} to ${to}`, columns, reportRows());
  }

  async function importReport(): Promise<ImportResult> {
    return blockedImport("NAFDAC statutory reports");
  }

  return (
    <div className="rounded-xl border border-[var(--color-border)] bg-white p-5">
      <div className="mb-4 flex flex-wrap items-center gap-3">
        <h3 className="font-semibold text-[var(--color-foreground)]">NAFDAC statutory reports</h3>
        <div className="ml-auto flex flex-wrap gap-2">
          {(["usage", "movements", "expiry", "supplier"] as const).map((r) => (
            <button key={r} type="button" onClick={() => setReport(r)}
              className={`focus-ring rounded-lg px-2.5 py-1.5 text-xs font-semibold ${report === r ? "bg-[var(--color-primary)] text-white" : "border border-[var(--color-border)] text-[var(--color-muted-fg)]"}`}>
              {r}
            </button>
          ))}
        </div>
      </div>
      <div className="mb-4 flex flex-wrap items-end gap-3">
        <label className="text-xs"><span className="mb-1 block font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">From</span><input type="date" className={inputCls} value={from} onChange={(e) => setFrom(e.target.value)} /></label>
        <label className="text-xs"><span className="mb-1 block font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">To</span><input type="date" className={inputCls} value={to} onChange={(e) => setTo(e.target.value)} /></label>
        {report === "expiry" && (
          <label className="text-xs"><span className="mb-1 block font-semibold uppercase tracking-wide text-[var(--color-muted-fg)]">Window (days)</span><input type="number" min={1} className={inputCls + " w-24"} value={days} onChange={(e) => setDays(Number(e.target.value))} /></label>
        )}
        <button type="button" onClick={() => void run()} disabled={loading} className={btnPrimary}>{loading ? "Loading…" : <><Activity size={14} />Run report</>}</button>
        <FilterBar
          query={search}
          onQueryChange={setSearch}
          from=""
          to=""
          onFromChange={() => undefined}
          onToChange={() => undefined}
          onClear={() => setSearch("")}
          searchPlaceholder="Search report rows…"
          searchWidth={200}
        />
        <ImportExportMenu
          entityLabel="NAFDAC Reports"
          exportCsv={exportCsv}
          exportPdf={exportPdf}
          importColumns={columns}
          templateFilename="nafdac-report-import-template.csv"
          onImport={importReport}
        />
      </div>
      {msg && <p className="mb-3 text-sm text-red-600">{msg}</p>}
      {loading ? (
        <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">Running {report} report…</p>
      ) : visibleRows.length === 0 ? (
        <p className="py-10 text-center text-sm text-[var(--color-muted-fg)]">No rows for this report / window.</p>
      ) : (
        <div className="max-h-[480px] overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="sticky top-0 border-b border-[var(--color-border)] bg-white text-xs uppercase tracking-wide text-[var(--color-muted-fg)]">
              <tr>{columns.map((c) => <th key={c} className="py-2 pr-3 font-semibold">{c}</th>)}</tr>
            </thead>
            <tbody className="divide-y divide-[var(--color-border)]">
              {visibleRows.map((r, i) => (
                <tr key={i}>{columns.map((c) => <td key={c} className="py-2 pr-3 text-[var(--color-muted-fg)]">{String(r[c] ?? "—")}</td>)}</tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}