"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Clock } from "lucide-react";
import ImportExportMenu from "@/components/ui/import-export-menu";
import type { ImportResult } from "@/components/ui/csv-import-modal";
import { dateStamp, downloadCsv, printTable } from "@/lib/export";
import { cardShell, errorBanner, flexWrapGap2 } from "@/lib/ui-constants";
import { inputCls, ngn, Stat } from "./pharmacy-shared";

// ---------------------------------------------------------------------------
// DAILY REPORT TAB - per-date sales summary by payment method + top drugs
// ---------------------------------------------------------------------------
interface DailyReport {
  date: string;
  total_sales: number;
  cash: number;
  pos: number;
  transfer: number;
  card: number;
  insurance: number;
  invoice_count: number;
  item_count: number;
  outstanding: number;
  top_drugs: Array<{ name: string; qty: number }>;
}

export function ReportTab({ viewOnly = false }: { viewOnly?: boolean }) {
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [report, setReport] = useState<DailyReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/pharmacy/reports/daily?date=${date}`, { cache: "no-store" });
      const body = await res.json();
      if (!res.ok) throw new Error(body.error ?? "Failed to load report");
      setReport(body.data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load report");
    } finally {
      setLoading(false);
    }
  }, [date]);

  useEffect(() => { void load(); }, [load]);

  const methods = useMemo(() => {
    if (!report) return [];
    return [
      ["Cash", report.cash],
      ["POS", report.pos],
      ["Transfer", report.transfer],
      ["Card", report.card],
      ["Insurance", report.insurance],
    ].filter(([, v]) => Number(v) > 0);
  }, [report]);

  const maxMethod = useMemo(() => Math.max(1, ...methods.map(([, v]) => Number(v))), [methods]);

  const REPORT_COLUMNS = ["date", "metric", "value"];

  const reportRows = () => {
    if (!report) return [];
    const out: (string | number)[][] = [
      [date, "total_sales", report.total_sales],
      [date, "invoice_count", report.invoice_count],
      [date, "item_count", report.item_count],
      [date, "outstanding", report.outstanding],
    ];
    for (const [label, value] of methods) out.push([date, String(label).toLowerCase(), Number(value)]);
    for (const d of report.top_drugs) out.push([date, `top_drug:${d.name}`, d.qty]);
    return out;
  };

  function exportCsv() {
    if (!report) { alert("Nothing to export â€” load the report for a date first."); return; }
    downloadCsv(`pharmacy-daily-report-${date}.csv`, REPORT_COLUMNS, reportRows());
  }

  function exportPdf() {
    if (!report) { alert("Nothing to export â€” load the report for a date first."); return; }
    printTable(`Pharmacy Daily Report â€” ${date}`, REPORT_COLUMNS, reportRows());
  }

  async function importReport(_rowsIn: string[][]): Promise<ImportResult> {
    return {
      created: 0,
      failed: 0,
      errors: ["The daily report is generated by the system from sales records and cannot be imported."],
    };
  }

  return (
    <div className="space-y-4">
      <div className={flexWrapGap2}>
        <label className="text-xs font-medium text-[var(--color-foreground)]" htmlFor="rp-date">Date</label>
        <input id="rp-date" type="date" value={date} onChange={(e) => setDate(e.target.value)} className={`${inputCls} w-auto`} />
        {loading && <Clock size={14} aria-hidden="true" className="animate-spin text-[var(--color-muted-fg)]" />}
        <ImportExportMenu
          entityLabel="Daily Report"
          exportCsv={exportCsv}
          exportPdf={exportPdf}
          importColumns={REPORT_COLUMNS}
          templateFilename="pharmacy-daily-report-import-template.csv"
          onImport={importReport}
          allowImport={!viewOnly}
        />
      </div>

      {error && <p role="alert" className={errorBanner}>{error}</p>}

      {report && (
        <>
          <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
            <Stat label="Total sales" value={ngn(report.total_sales)} tone="ok" />
            <Stat label="Invoices" value={report.invoice_count} />
            <Stat label="Items sold" value={report.item_count} />
            <Stat label="Outstanding" value={ngn(report.outstanding)} tone={report.outstanding > 0 ? "warn" : "ok"} />
          </div>

          <div className="grid gap-5 lg:grid-cols-2">
            <div className={cardShell}>
              <h3 className="text-sm font-bold text-[var(--color-foreground)]">By payment method</h3>
              {methods.length === 0 ? (
                <p className="py-6 text-center text-xs text-[var(--color-muted-fg)]">No sales on this day.</p>
              ) : (
                <div className="mt-3 space-y-2">
                  {methods.map(([label, value]) => (
                    <div key={label as string}>
                      <div className="flex items-center justify-between text-xs">
                        <span className="font-medium">{label}</span>
                        <span className="font-semibold">{ngn(Number(value))}</span>
                      </div>
                      <div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100">
                        <div
                          className="h-full rounded-full bg-[var(--color-primary)]"
                          style={{ width: `${(Number(value) / maxMethod) * 100}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className={cardShell}>
              <h3 className="text-sm font-bold text-[var(--color-foreground)]">Top drugs</h3>
              {report.top_drugs.length === 0 ? (
                <p className="py-6 text-center text-xs text-[var(--color-muted-fg)]">No items sold on this day.</p>
              ) : (
                <ul className="mt-3 space-y-2">
                  {report.top_drugs.map((d, i) => (
                    <li key={i} className="flex items-center justify-between gap-2 rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm">
                      <span className="min-w-0 truncate font-medium">{d.name}</span>
                      <span className="shrink-0 text-xs text-[var(--color-muted-fg)]">{d.qty} unit(s)</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
